<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdController::delete' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\AdController::edit' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\AdController::show' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\AdminAdController::delete' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\AdminAdController::edit' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\AdminAdController::index' => ['privates', '.service_locator.UAhKzwz', 'get_ServiceLocator_UAhKzwzService.php', true],
    'App\\Controller\\AdminBookingController::delete' => ['privates', '.service_locator.l8ZYTzR', 'get_ServiceLocator_L8ZYTzRService.php', true],
    'App\\Controller\\AdminBookingController::edit' => ['privates', '.service_locator.l8ZYTzR', 'get_ServiceLocator_L8ZYTzRService.php', true],
    'App\\Controller\\AdminBookingController::index' => ['privates', '.service_locator.UAhKzwz', 'get_ServiceLocator_UAhKzwzService.php', true],
    'App\\Controller\\AdminCommentController::delete' => ['privates', '.service_locator.Gn3oxQ2', 'get_ServiceLocator_Gn3oxQ2Service.php', true],
    'App\\Controller\\AdminCommentController::edit' => ['privates', '.service_locator.Gn3oxQ2', 'get_ServiceLocator_Gn3oxQ2Service.php', true],
    'App\\Controller\\AdminCommentController::index' => ['privates', '.service_locator.UAhKzwz', 'get_ServiceLocator_UAhKzwzService.php', true],
    'App\\Controller\\AdminDashboardController::index' => ['privates', '.service_locator.7OlG3K4', 'get_ServiceLocator_7OlG3K4Service.php', true],
    'App\\Controller\\AdminUserController::delete' => ['privates', '.service_locator.W8gcBWH', 'get_ServiceLocator_W8gcBWHService.php', true],
    'App\\Controller\\AdminUserController::edit' => ['privates', '.service_locator.W8gcBWH', 'get_ServiceLocator_W8gcBWHService.php', true],
    'App\\Controller\\AdminUserController::login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\BookingController::book' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\BookingController::show' => ['privates', '.service_locator.l8ZYTzR', 'get_ServiceLocator_L8ZYTzRService.php', true],
    'App\\Controller\\HomeController::index' => ['privates', '.service_locator.RUUfoyn', 'get_ServiceLocator_RUUfoynService.php', true],
    'App\\Controller\\UserController::login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
    'App\\Controller\\UserController::updatePassword' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
    'App\\Controller\\UserPageController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\AdController:delete' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\AdController:edit' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\AdController:show' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\AdminAdController:delete' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\AdminAdController:edit' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\AdminAdController:index' => ['privates', '.service_locator.UAhKzwz', 'get_ServiceLocator_UAhKzwzService.php', true],
    'App\\Controller\\AdminBookingController:delete' => ['privates', '.service_locator.l8ZYTzR', 'get_ServiceLocator_L8ZYTzRService.php', true],
    'App\\Controller\\AdminBookingController:edit' => ['privates', '.service_locator.l8ZYTzR', 'get_ServiceLocator_L8ZYTzRService.php', true],
    'App\\Controller\\AdminBookingController:index' => ['privates', '.service_locator.UAhKzwz', 'get_ServiceLocator_UAhKzwzService.php', true],
    'App\\Controller\\AdminCommentController:delete' => ['privates', '.service_locator.Gn3oxQ2', 'get_ServiceLocator_Gn3oxQ2Service.php', true],
    'App\\Controller\\AdminCommentController:edit' => ['privates', '.service_locator.Gn3oxQ2', 'get_ServiceLocator_Gn3oxQ2Service.php', true],
    'App\\Controller\\AdminCommentController:index' => ['privates', '.service_locator.UAhKzwz', 'get_ServiceLocator_UAhKzwzService.php', true],
    'App\\Controller\\AdminDashboardController:index' => ['privates', '.service_locator.7OlG3K4', 'get_ServiceLocator_7OlG3K4Service.php', true],
    'App\\Controller\\AdminUserController:delete' => ['privates', '.service_locator.W8gcBWH', 'get_ServiceLocator_W8gcBWHService.php', true],
    'App\\Controller\\AdminUserController:edit' => ['privates', '.service_locator.W8gcBWH', 'get_ServiceLocator_W8gcBWHService.php', true],
    'App\\Controller\\AdminUserController:login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\BookingController:book' => ['privates', '.service_locator.5BH.j.y', 'get_ServiceLocator_5BH_J_YService.php', true],
    'App\\Controller\\BookingController:show' => ['privates', '.service_locator.l8ZYTzR', 'get_ServiceLocator_L8ZYTzRService.php', true],
    'App\\Controller\\HomeController:index' => ['privates', '.service_locator.RUUfoyn', 'get_ServiceLocator_RUUfoynService.php', true],
    'App\\Controller\\UserController:login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
    'App\\Controller\\UserController:updatePassword' => ['privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true],
    'App\\Controller\\UserPageController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
